lecture-3-pdp-add2cart
MrHedgehogBY/phoneshop-servlet-api pull request #4
Opened 2021-02-15 06:26 UTC by MrHedgehogBY

lecture 3 tasks completed

2021-02-16 16:57 UTC, alexandr-i requested changes

2021-02-16 16:57 UTC, alexandr-i commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +        }
мультикэтч?

2021-02-16 16:57 UTC, alexandr-i commented on src/main/java/com/es/phoneshop/web/ServiceGetter.java
> +        synchronized (session) {
В чатах кидали ссылку на правильную синхр по сессии
там или либку заюзать или просто иметь свой лок объект в сессии и по нему синкаться,
сама сессия может быть врапнута и отличаться

2021-02-16 16:57 UTC, alexandr-i commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +        }
чёта дубликация в кэтчах
или в файнали перенеси или подумай ещё как

2021-02-16 21:10 UTC, MrHedgehogBY commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +        }
исправил

2021-02-16 21:10 UTC, MrHedgehogBY commented on src/main/java/com/es/phoneshop/web/ServiceGetter.java
> +        synchronized (session) {
сделал через mutex

2021-02-17 12:22 UTC, alexandr-i approved these changes

2021-02-17 12:23 UTC, merged