lecture-5-checkout-page-no-refactoring
MrHedgehogBY/phoneshop-servlet-api pull request #6
Opened 2021-02-25 09:05 UTC by MrHedgehogBY

lecture 5 tasks completed

2021-03-01 13:59 UTC, alexandr-i requested changes

2021-03-01 13:59 UTC, alexandr-i commented on src/main/java/com/es/phoneshop/dao/ItemDao.java
> +public abstract class ItemDao {
Наверное всё таки не DAO

2021-03-01 13:59 UTC, alexandr-i commented on pom.xml
> +        <dependency>
можнобыло простым регеспом на +ХХХХХХХ

2021-03-01 13:59 UTC, alexandr-i commented on pom.xml
> +        <dependency>
либы мы типа не юзаем

2021-03-01 13:59 UTC, alexandr-i commented on src/main/java/com/es/phoneshop/dao/ArrayListOrderDao.java
> +    public void clear() {
в чём тогда отличие clear от clearItems?

2021-03-01 13:59 UTC, alexandr-i commented on src/main/java/com/es/phoneshop/dao/ArrayListOrderDao.java
> +        items = new ArrayList<>();
перенести в супера

2021-03-01 13:59 UTC, alexandr-i commented on src/main/java/com/es/phoneshop/dao/ArrayListProductDao.java
> +        return getItem(id);
думаю ко всем CRUD методам можно их обозвать без item и юзать напрямую в сервисах без проброски этой

2021-03-01 13:59 UTC, alexandr-i commented on src/main/java/com/es/phoneshop/dao/ArrayListProductDao.java
>      public void delete(Long id) {
почему в абстрактом не получилось так?

2021-03-01 13:59 UTC, alexandr-i commented on src/main/java/com/es/phoneshop/model/order/DefaultOrderService.java
> +        orderDao.save(order);
а если F5 на странице, у нас откроется сохранённый ордер?*

2021-03-01 13:59 UTC, alexandr-i commented on src/main/java/com/es/phoneshop/model/security/DefaultDosProtectionService.java
> +        if (System.currentTimeMillis() - timeMap.get(ip) > 60000) {
magic numbers

2021-03-01 13:59 UTC, alexandr-i commented on src/main/webapp/WEB-INF/pages/cart.jsp
> +    <c:if test="${not empty param.message or not empty param.errorMessage}">
т.е. обе секции буду если хоть 1но условие?

2021-03-01 13:59 UTC, alexandr-i commented on src/main/webapp/WEB-INF/pages/checkout.jsp
> +    </c:if>
вообще это часто гдже можно было в отдельный тэг

2021-03-01 13:59 UTC, alexandr-i commented on src/main/webapp/WEB-INF/pages/checkout.jsp
> +                <td class="price">
а если 5 штук, цена будет за одну или уже за все?

2021-03-01 13:59 UTC, alexandr-i commented on src/main/webapp/WEB-INF/pages/checkout.jsp
> +                        </c:forEach>
можно было 1н раз цикл только для нужно ставить атрибут в теге selected

2021-03-03 20:08 UTC, MrHedgehogBY commented on src/main/java/com/es/phoneshop/dao/ItemDao.java
> +public abstract class ItemDao {
Переименовал

2021-03-03 20:08 UTC, MrHedgehogBY commented on pom.xml
> +        <dependency>
реализовал через регекспы

2021-03-03 20:09 UTC, MrHedgehogBY commented on src/main/java/com/es/phoneshop/dao/ArrayListOrderDao.java
> +    public void clear() {
убрал этот метод, юзаю clear() из абстрактного

2021-03-03 20:09 UTC, MrHedgehogBY commented on src/main/java/com/es/phoneshop/dao/ArrayListOrderDao.java
> +        items = new ArrayList<>();
сделал

2021-03-03 20:09 UTC, MrHedgehogBY commented on src/main/java/com/es/phoneshop/dao/ArrayListProductDao.java
> +        return getItem(id);
исправил

2021-03-03 20:10 UTC, MrHedgehogBY commented on src/main/java/com/es/phoneshop/dao/ArrayListProductDao.java
>      public void delete(Long id) {
использую реализацию в абстрактном

2021-03-03 20:16 UTC, MrHedgehogBY commented on src/main/java/com/es/phoneshop/model/order/DefaultOrderService.java
> +        orderDao.save(order);
Да, при обновлении страницы всё гуд, т.к. order сохраняется в лист ордеров в процессе работы doPost метода из CheckoutPageServlet, в конце которого идёт редирект на doGet из OrderOverviewServlet. Здесь уже нужный ордер ищется по id и при обновлении страницы мы просто кидаем гет запрос, который и попадает в orderOverviewServlet.

2021-03-03 20:18 UTC, MrHedgehogBY commented on src/main/java/com/es/phoneshop/model/security/DefaultDosProtectionService.java
> +        if (System.currentTimeMillis() - timeMap.get(ip) > 60000) {
убрал

2021-03-03 20:18 UTC, MrHedgehogBY commented on src/main/webapp/WEB-INF/pages/cart.jsp
> +    <c:if test="${not empty param.message or not empty param.errorMessage}">
сделал секции отдельно

2021-03-03 20:19 UTC, MrHedgehogBY commented on src/main/webapp/WEB-INF/pages/checkout.jsp
> +    </c:if>
вынес

2021-03-03 20:19 UTC, MrHedgehogBY commented on src/main/webapp/WEB-INF/pages/checkout.jsp
> +                <td class="price">
Да, цена была за одну, исправил, сейчас уже за все)

2021-03-03 20:19 UTC, MrHedgehogBY commented on src/main/webapp/WEB-INF/pages/checkout.jsp
> +                        </c:forEach>
сделал

2021-03-06 20:29 UTC, alexandr-i commented on src/main/webapp/WEB-INF/pages/checkout.jsp
> +                        </c:forEach>
а тут не будет дубликатов?? вроде как 1н метод 2 раза будет. Или браузер жто пофиксит?
Я думал всё сделать просто в в цикле и внетри цекла проверка что бы ставить или нет selected на элементе

2021-03-06 20:29 UTC, merged

2021-03-06 20:40 UTC, MrHedgehogBY commented on src/main/webapp/WEB-INF/pages/checkout.jsp
> +                        </c:forEach>
Да, в случае если там уже есть какое-то значение, получается дубликат. Переделаю так, как Вы сказали. Насколько я понял, уже без pr?

2021-03-06 21:19 UTC, MrHedgehogBY commented on src/main/webapp/WEB-INF/pages/checkout.jsp
> +                        </c:forEach>
![изображение](https://user-images.githubusercontent.com/61331766/110221006-a029db00-7eda-11eb-8328-045e0083eb24.png)
Сделал таким образом